<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="   crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <script src="<?php echo $basePath ?>/js/process.js"></script>
    </head>
    <body>
        <div class="container">
          
          <div class="masthead">
            <h3 class="text-muted">2048 Simulator</h3>
          </div>
          
          <!-- Jumbotron -->
          <div class="jumbotron">
            <h1>2048 Simulator</h1>
            <p class="lead">Simula las operaciones del juego 2048</p>
          </div>

          <!-- Example row of columns -->
          <div class="row">
            <div class="col-lg-6">
              <h2>¡Introduce tu información!</h2>
              <p class="text-info">
                  Las primeras 4 líneas contienen 4 enteros separados por un espacio y que representan el estado inicial del juego. Cada valor es una potencia de dos menor o igual a 2048 o un 0 si es
￼                 que no hay una casilla en ese lugar.
              </p>
              <p class="text-info"> 
                  Posteriormente se da un entero entero M​,​con 1​≤M≤10^5​
                  que indica la cantidad de movimientos que seguirán. Las próximas M​ líneas contienen alguna
                  de las siguientes palabras: A​rriba, Abajo, Izquierda, Derecha indicando el movimiento a realizar.
              </p>
              <form id="sender">
                  <div class="form-group">
                    <textarea id="rules" rows="10" class="form-control"></textarea>
                  </div>
                  <button type="submit" class="btn btn-default">Submit</button>
              </form>
            </div>
            <div class="col-lg-6">
              <h2>Resultado</h2>
              <p class="text-success"> 
                  4 líneas cada una con 4 enteros separados por un espacio, que representan el estado final del juego 2048 después de haber realizado los movimientos partiendo de la configuración inicial.
              </p>
              <form>
                  <div class="form-group">
                    <textarea rows="10" disabled class="form-control" id="result"></textarea>
                  </div>
              </form>
           </div>
          </div>

          <footer class="footer">
            <p>&copy; 2016 Isaac Cruz Ramirez.</p>
          </footer>

        </div>
    </body>
</html>
